# Generated by Django 4.0.6 on 2022-08-01 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField(default=datetime.datetime(2022, 7, 31, 23, 46, 15, 114759))),
            ],
        ),
    ]
